### ISSUE TITLE
can be fade in/out the images?

### ISSUE THREAD

**Issue by eltonec** [ZouYouShun/ngx-hm-carousel#9]

**Comment by ZouYouShun** [comment]
Hi @eltonec , the easy you can do that with pure css animation.

Here is an [example](https://ngx-hm-carousel-fade-example.stackblitz.io) below.
https://stackblitz.com/edit/ngx-hm-carousel-fade-example

If you change the animation time, you must set `[aniTime]` with `ngx-hm-carousel`, otherwise it will cause the animation break.

```css
     $transition_time:.4s;

    .item {
      width: 100%;
      display: block;
      // fade
      opacity: 0;

      // using delay to prevent left change show error
      &.fade_animation {
        transition: opacity 0.295s linear $transition_time;
      }

      &.visible {
        opacity: 1;
      }

      .img {
        width: 100%;
        display: block;
        background-size: cover;
        background-position: center;
        height: 0;
        padding-bottom: 50%;
      }
    }
```
